# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, # You can obtain one at http://mozilla.org/MPL/2.0/.

# This script formats and exports schema files by markdown for the docs site.
#
# webextensions spec: https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/schema.html
# typedoc spec: https://typedoc.org/documents/Tags.html
# xpidl spec: https://firefox-source-docs.mozilla.org/xpcom/xpidl.html
#
# The markdown design is based on MDN: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/action

import json
import os
import shutil
import textwrap

# direcotry
here = os.path.abspath(os.path.dirname(__file__))
print(here)
topsrcdir = os.path.abspath(os.path.dirname(os.path.dirname(here)))

# repository
repository_name = 'gecko-dev-for-ssi'
repository_url = f"https://gitlab.com/studioteatwo/{repository_name}/-/blob/mvp/"
doc_list = [
    'browser/components/extensions/schemas/ssi/ssi.json',
    'browser/components/extensions/schemas/ssi/ssi.nostr.json',
    'toolkit/components/ssi/nsICredentialInfo.idl',
    'toolkit/components/ssi/nsICredentialMetaInfo.idl',
    'tools/ssi/output/window.ssi.json' # generated by `npm run doc` in `browser/extensions/ssi`
]
file_paths = []
for doc in doc_list:
    file_paths.append(os.path.join(topsrcdir, doc))

# output
output_directory = os.path.join(topsrcdir, "tools/ssi/output")
if not os.path.exists(output_directory):
    os.makedirs(output_directory)
idl_directory = os.path.join(output_directory, "core")
if os.path.exists(idl_directory):
    shutil.rmtree(idl_directory)
os.makedirs(idl_directory)


def xpidl(file_path):
    file_name = os.path.basename(file_path).replace(".idl", "")
    output_file_path = os.path.join(topsrcdir, idl_directory, f"{file_name}.md")

    print(f"-----{file_name}-----")

    top_line = [f"# {file_name}\n\n"] + ["This is described in [XPIDL](https://firefox-source-docs.mozilla.org/xpcom/xpidl.html) that is an Interface Description Language used to specify XPCOM interface classes.\n\n"]

    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            lines = file.readlines()

        # assume license
        lines = lines[4:]

        delete_conditions = [
            "#include",
            "#define",
            "[scriptable",
            "%",
        ]
        filtered_lines = [
            line for line in lines
            if not any(line.startswith(condition) for condition in delete_conditions)
        ]
        filtered_lines = remove_empty_lines(filtered_lines)

        print(f"filtered_lines: {len(filtered_lines)}")

        output_lines = top_line + ['```c++\n'] + filtered_lines + ['```\n\n'] + [get_repository_text(file_name)]

        with open(output_file_path, 'w', encoding='utf-8') as output_file:
            output_file.writelines(output_lines)

        print(f"-----end:{file_name}-----")

    except FileNotFoundError:
        print(f"Error: The file {file_path} was not found.")
    except Exception as e:
        print(f"Error: An unexpected error occurred while processing {file_path} - {e}")


def webextensions(file_name, file_path):
    output_file_path = os.path.join(here, output_directory, f"browser.{file_name}", "README.md")

    print(f"-----browser.{file_name}-----")

    try:
        with open(file_path, 'r', encoding='utf-8') as json_file:
            data = json.load(json_file)

        # Returns the text of the summary and create each member file nested inside it.
        summary_text = build_browser(data)

        with open(output_file_path, 'w', encoding='utf-8') as output_file:
            output_file.write(summary_text)

        print(f"-----end:{file_name}-----")

    except FileNotFoundError:
        print(f"Error: The file {file_path} was not found.")
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON format in {file_path}.")
    except Exception as e:
        print(f"Error: An unexpected error occurred while processing {file_path} - {e}")


def build_browser(data):
    output_text = ''
    for item in data:
        if item["namespace"] == "manifest":
            continue

        output_text += f"# {item['namespace']}\n\n"

        if 'description' in item:
            output_text += f"{item['description']}\n\n"

        if 'permissions' in item:
            output_text += "## Required Permissions\n\n"
            output_text += f"`{item['permissions']}`\n\n"

        for key in ['types', 'properties', 'functions', 'events']:
            if key in item:
                print(f"{key.capitalize()}")
                output_text += f"## {key.capitalize()}{'()' if type == 'functions' else ''}\n\n"

                for sub_item in item[key]:
                    name = 'id' if key == 'types' else 'name'
                    print(f"[build]: {sub_item[name]} proceeds...")
                    output_text += f"### [{sub_item[name]}]({sub_item[name]}.md)\n\n"

                    if 'description' in sub_item:
                        output_text += f"{sub_item['description']}\n\n"

                    create_member_file(item['namespace'], key, sub_item)

        output_text += get_repository_text(item['namespace'])

    return output_text

def create_member_file(namespace, type, data):
    key = 'id' if type == 'types' else 'name'
    print(f"[create_member]: {type} {namespace}.{data[key]} proceeds...")

    output_file_path = os.path.join(here, output_directory, f"browser.{namespace}", f"{data[key]}.md")
    output_text = f"# {namespace}.{data[key]}{'()' if type == 'functions' else ''}\n\n"

    if 'description' in data:
        output_text += f"{data['description']}\n\n"

    if 'async' in data:
        output_text += "This is an asynchronous function that returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).\n\n"

    if type in ['functions', 'events'] :
        output_text += '## Syntax\n\n'
        output_text += f"{build_syntax(namespace, type, data)}\n\n"
    elif type == 'types':
        output_text += "## Type\n\n"
        output_text += f"{build_types(data['properties'])}"
    # type == 'Properties' is not implemented.

    if 'parameters' in data:
        if type == 'events':
            output_text += "## addListener syntax\n\n"
        output_text += "### Parameters\n\n"
        output_text += f"{build_parameters(data['parameters'])}"

    if 'returns' in data:
        output_text += "### Return value\n\n"
        output_text += f"{data['returns']['description']}\n\n"

    if type in ['functions', 'events'] :
        output_text += f"## Examples\n\n{{{{#include fragments/examples_{data[key]}.md }}}}\n\n"

    output_text += get_repository_text(namespace)

    with open(output_file_path, 'w', encoding='utf-8') as output_file:
        output_file.write(output_text)

def build_parameters(data):
    output_text = ''
    for item in data:
        print(f"[build_parameters]: {item['name']} proceeds...")

        output_text += f"#### `{item['name']}`"
        if 'optional' in item and item['optional']:
            output_text += ' (optional)'
        output_text += '\n\n'

        type = item['$ref'] if '$ref' in item else item['type']
        output_text += f"`{type}`. {item['description']}\n\n"

        if 'type' in item and item['type'] == 'object':
            property = item['properties']
            for key in property:
                output_text += f"> ##### {key}"
                if 'optional' in property[key] and property[key]['optional']:
                    output_text += ' (optional)'
                output_text += '\n>\n'

                output_text += f"> `{property[key]['type']}`. {property[key]['description']}\n>\n"
            output_text += '\n'

    if len(data) == 0:
        output_text += 'None.\n\n'

    return output_text

def build_types(data):
    output_text = ''
    for key in data:
        print(f"[build_types]: {key} proceeds...")

        value = data[key]
        output_text += f"### `{key}`"
        if 'optional' in value and value['optional']:
            output_text += ' (optional)'
        output_text += '\n\n'

        output_text += f"`{value['type']}`. {value['description']}\n\n"

    return output_text

def build_syntax(namespace, type, data):
    if type == 'events':
        function_name = f"browser.{namespace}.{data['name']}"
        return textwrap.dedent('''\
            ```js
            {function_name}.addListener(listener)
            {function_name}.removeListener(listener)
            {function_name}.hasListener(listener)
            ```

            Events have three functions:

            `addListener(listener)`
            Adds a listener to this event.

            `removeListener(listener)`
            Stop listening to this event. The listener argument is the listener to remove.

            `hasListener(listener)`
            Check whether listener is registered for this event. Returns `true` if it is listening, `false` otherwise.
        ''').format(function_name=function_name).strip()

    # functions
    output_text = "```js\n"
    return_value = ''
    if 'returns' in data:
        return_name = 'object' if '$ref' in data['returns'] else data['returns']['type']
        return_value += f"const {return_name}Value = "

    if len(data['parameters']) == 0:
        output_text += f"{return_value}{'await' if data.get('async') else ''} browser.{namespace}.{data['name']}()\n"
        output_text += "```\n"
        return output_text

    output_text += f"{return_value}{'await' if data['async'] else ''} browser.{namespace}.{data['name']}(\n"

    for param in data['parameters']:
        output_text += f"\t{param['name']}, // {'optional ' if param.get('optional') else ''}{'object' if param.get('$ref') else param['type']}\n"

    output_text += ")\n```\n"

    return output_text


def typedoc(file_path):
    try:
        file_name = os.path.basename(file_path).replace(".json", "")
        with open(file_path, 'r', encoding='utf-8') as json_file:
            data = json.load(json_file)

        # Returns the text of the summary and create each member file nested inside it.
        summary_text = build_window(file_name, data)

    except FileNotFoundError:
        print(f"Error: The file {file_path} was not found.")
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON format in {file_path}.")
    except Exception as e:
        print(f"Error: An unexpected error occurred while processing {file_path} - {e}")

def build_window(file_name, jsondata):
    switch_dict = {
        'WindowSSI': 'ssi',
        'WindowSSINostr': 'ssi.nostr',
    }
    window_data = [node for node in jsondata['children'] if node['name'] in ['WindowSSI', 'WindowSSINostr']]
    for data in window_data:
        namespace = switch_dict.get(data['name'])

        sub_directory = os.path.join(output_directory, f"window.{namespace}")
        if os.path.exists(sub_directory):
            shutil.rmtree(sub_directory)
        os.makedirs(sub_directory)
        output_file_path = os.path.join(sub_directory, "README.md")

        print(f"-----window.{namespace}-----")

        output_text = ''

        output_text += f"# {namespace}\n\n"
        for node in data['comment']['summary']:
            output_text += node["text"]
        output_text += "\n\n"

        types_data = []
        if namespace == 'ssi.nostr':
            types_data = [node for node in jsondata['children'] if node['name'].startswith('Nostr')]
        if len(types_data) > 0:
            output_text += "## Types\n\n"
            for node in types_data:
                output_text += f"### [{node['name']}]({node['name']}.md)\n\n"
                if 'comment' in node:
                    for node2 in node['comment']['summary']:
                        output_text += node2["text"]
                    output_text += "\n\n"
                create_member_file_window(namespace, node['kind'], node)

        properties_data = [node for node in data['children'] if node['kind'] == 1024 and node['name'].startswith('_') == False]
        if len(properties_data) > 0:
            for node in properties_data:
                if 'name' in node and node['name'] not in ['nostr']:
                    create_member_file_window(namespace, node['kind'], node)

        functions_data = [node for node in data['children'] if node['kind'] == 2048 and node['name'].startswith('_') == False]
        if len(functions_data) > 0:
            output_text += "## Functions\n\n"
            for node in functions_data:
                output_text += f"### [{node['name']}()]({node['name']}.md)\n\n"
                signature = node['signatures'][0]
                if node['name'] not in ['addEventListener', 'removeEventListener']:
                    for node2 in signature['comment']['summary']:
                        output_text += node2["text"]
                    output_text += "\n\n"
                create_member_file_window(namespace, node['kind'], signature)

        output_text += get_repository_text(f"window.{namespace}")

        with open(output_file_path, 'w', encoding='utf-8') as output_file:
            output_file.write(output_text)

        print(f"-----end:{file_name}-----")

def create_member_file_window(namespace, kind, data):
    sub_directory = os.path.join(output_directory, f"window.{namespace}")
    output_file_path = os.path.join(sub_directory, f"{data['name']}.md")

    print(f"[build_memebers]: {data['name']} proceeds...")

    output_text = ''

    output_text += f"# {namespace}.{data['name']}"
    if kind == 2048:
        output_text += '()'
    output_text += '\n\n'

    if kind == 2097152:
        output_text += f"```admonish attention\nThis is the difinition on TypeScript, does not exist in the execution environment. It's just a documentation commentary.\n```\n\n"

    if 'comment' in data:
        for node in data['comment']['summary']:
            output_text += node["text"]
        output_text += "\n\n"

    # Type
    if kind == 2097152:
        output_text += '## Type\n\n'
        output_text += f"`{data['type']['type']}`\n\n"

        output_text += '## Values\n\n'
        if 'value' in data['type']:
            output_text += f"### {data['type']['value']}\n\n"
            output_text += f"`{data['type']['type']}`.\n\n"
        elif 'types' in data['type']:
            for type in data['type']['types']:
                output_text += f"### {type['value']}\n\n"
                output_text += f"`{type['type']}`.\n\n"

    elif kind == 2048:
        if data['name'] not in ['addEventListener', 'removeEventListener']:

            output_text += '## Syntax\n\n'
            output_text += "```js\n"
            return_value = ''
            if 'type' in data and 'name' in data['type'] and data['type']['name'] != 'void':
                return_value += f"const {data['type']['name'].lower()}Value = "
            elif 'type' in data and 'name' not in data['type']:
                return_value += f"const objectValue = "

            if len(data['parameters']) == 0:
                output_text += f"{return_value}{'await' if 'name' in data['type'] and data['type']['name'] == 'Promise' else ''} window.{namespace}.{data['name']}("
                output_text += "```\n"
            else:
                output_text += f"{return_value}{'await' if 'name' in data['type'] and data['type']['name'] == 'Promise' else ''} window.{namespace}.{data['name']}(\n"
                for param in data['parameters']:
                    output_text += f"\t{param['name']}, // {'optional ' if 'flags' in param and 'isOptional' in param['flags'] else ''}{'object' if 'name' not in param['type'] else param['type']['name']}\n"

            output_text += ")\n```\n\n"


            output_text += '### Parameters\n\n'
            if len(data['parameters']) == 0:
                output_text += 'none.\n\n'
            for node in data['parameters']:
                output_text += f"#### {node['name']}"
                if 'isOptional' in node['flags']:
                    output_text += '(optional)'
                output_text += '\n\n'
                if 'name' in node['type']:
                    output_text += f"`{node['type']['name']}`."
                    for node2 in node['comment']['summary']:
                        output_text += node2["text"]
                    output_text += '\n'
                elif 'declaration' in node['type']:
                    output_text += "`object`."
                    for node2 in node['comment']['summary']:
                        output_text += node2["text"]
                    output_text += '\n\n'

                    parameters = []
                    if 'children' in node['type']['declaration']:
                        parameters = node['type']['declaration']['children']
                    elif 'signatures' in node['type']['declaration'] and "parameters" in node['type']['declaration']['signatures'][0]:
                        parameters = node['type']['declaration']['signatures'][0]["parameters"]
                    for node2 in parameters:
                        output_text += f"> ##### {node2['name']}"
                        if 'isOptional' in node2['flags']:
                            output_text += '(optional)'
                        output_text += '\n>\n'
                        if 'name' in node2['type']:
                            output_text += f"> `{node2['type']['name']}`. "
                        elif 'value' in node2['type']:
                            output_text += f"> `{node2['type']['value']}`. "
                        if 'comment' in node2:
                            for node3 in node2['comment']['summary']:
                                output_text += node3['text']
                        output_text += '\n>\n'

                output_text += '\n'

            output_text += '### Return value\n\n'
            returns = [node for node in data['comment'].get('blockTags', []) if node['tag'] == '@returns']
            if len(returns) > 0:
                for node in returns[0]['content']:
                    output_text += node['text']
            else:
                output_text += 'None ([undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined)).'
            output_text += "\n\n"

            throws = [node for node in data['comment'].get('blockTags', []) if node['tag'] == '@throws']
            if len(throws) > 0:
                output_text += '### Exceptions\n\n'
                for node in throws[0]['content']:
                    output_text += f"Throw error {node['text']}"
            output_text += "\n\n"

            output_text += f"## Examples\n\n{{{{#include fragments/examples_{data['name']}.md }}}}\n\n"

    output_text += get_repository_text(f"window.{namespace}")

    with open(output_file_path, 'w', encoding='utf-8') as output_file:
        output_file.write(output_text)


def get_repository_text(namespace):
    repository = repository_url
    window_ts_file = 'browser/extensions/ssi/src/window.ssi.type.ts'
    if namespace == 'ssi':
        repository += doc_list[0]
        ext = 'json'
    elif namespace == "ssi.nostr":
        repository += doc_list[1]
        ext = 'json'
    elif namespace == "nsICredentialInfo":
        repository += doc_list[2]
        ext = 'idl'
    elif namespace == "nsICredentialMetaInfo":
        repository += doc_list[3]
        ext = 'idl'
    elif namespace.startswith('window.'):
        namespace = 'window.ssi'
        repository += window_ts_file
        ext = 'type.ts'

    return f"```admonish\nThis documentation is derived from [{namespace}.{ext}]({repository}) in {repository_name}.\n```\n\n"

def remove_empty_lines(lines):
    start = 0
    while start < len(lines) and not lines[start].strip():
        start += 1

    end = len(lines) - 1
    while end >= start and not lines[end].strip():
        end -= 1

    return lines[start:end + 1]


def main():
    for file_path in file_paths:
        if '.idl' in os.path.basename(file_path):
            xpidl(file_path)
        elif 'window.ssi.json' in os.path.basename(file_path):
            typedoc(file_path)
        else:
            file_name = os.path.basename(file_path).replace(".json", "")
            sub_directory = os.path.join(output_directory, f"browser.{file_name}")
            if os.path.exists(sub_directory):
                shutil.rmtree(sub_directory)
            os.makedirs(sub_directory)
            webextensions(file_name, file_path)

main()
