/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */


#include "nsISupports.idl"
#include "nsISsiPromptInstance.idl"

interface nsICredentialInfo;
interface nsIDOMWindow;

webidl Element;

[scriptable, uuid(194fe61c-e33b-4f60-8165-1112da3176d1)]
interface nsISsiPrompter : nsISupports {

  /**
   * Ask the user if they want to save a credential (Yes, Never, Not Now)
   *
   * @param aBrowser
   *        The browser of the webpage request that triggered the prompt.
   * @param aCredential
   *        The credential to be saved.
   * @param dismissed
   *        A boolean value indicating whether the save credentials doorhanger should
   *        be dismissed automatically when shown.
   * @param notifySaved
   *        A boolean value indicating whether the notification should indicate that
   *        a credential has been saved
   * @param autoFilledCredentialGuid
   *        A string guid value for the credential which was autofilled into the form
   * @param possibleValues
   *        Contains values from anything that we think, but are not sure, might be
   *        a username or password.  Has two properties, 'usernames' and 'passwords'.
   */
  nsISsiPromptInstance promptToSavePassword(
          in Element aBrowser,
          in nsICredentialInfo aCredential,
          [optional] in boolean dismissed,
          [optional] in boolean notifySaved,
          [optional] in AString autoFilledCredentialGuid,
          [optional] in jsval possibleValues);

  /**
   * Ask the user if they want to change a credential's password or username.
   * If the user consents, modifyCredential() will be called.
   *
   * @param aBrowser
   *        The browser of the webpage request that triggered the prompt.
   * @param aOldCredential
   *        The existing credential (with the old password).
   * @param aNewCredential
   *        The new credential.
   * @param dismissed
   *        A boolean value indicating whether the save credentials doorhanger should
   *        be dismissed automatically when shown.
   * @param autoSavedCredentialGuid
   *        A string guid value for the old credential to be removed if the changes
   *        match it to a different credential
   * @param autoFilledCredentialGuid
   *        A string guid value for the credential which was autofilled into the form
   * @param possibleValues
   *        Contains values from anything that we think, but are not sure, might be
   *        a username or password.  Has two properties, 'usernames' and 'passwords'.
   */
  nsISsiPromptInstance promptToChangePassword(
          in Element aBrowser,
          in nsICredentialInfo aOldCredential,
          in nsICredentialInfo aNewCredential,
          [optional] in boolean dismissed,
          [optional] in boolean notifySaved,
          [optional] in AString autoSavedCredentialGuid,
          [optional] in AString autoFilledCredentialGuid,
          [optional] in jsval possibleValues);

  /**
   * Ask the user if they want to change the password for one of
   * multiple credentials, when the caller can't determine exactly which
   * credential should be changed. If the user consents, modifyCredential() will
   * be called.
   *
   * @param aBrowser
   *        The browser of the webpage request that triggered the prompt.
   * @param credentials
   *        An array of existing credentials.
   * @param aNewCredential
   *        The new credential.
   *
   * Note: Because the caller does not know the username of the credential
   *       to be changed, aNewCredential.username and aNewCredential.usernameField
   *       will be set (using the user's selection) before modifyCredential()
   *       is called.
   */
  nsISsiPromptInstance promptToChangePasswordWithUsernames(
          in Element aBrowser,
          in Array<nsICredentialInfo> credentials,
          in nsICredentialInfo aNewCredential);
};
