name: cleanup all caches
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          set -e
          echo "Deleting caches..."

          i=1
          while [ "$i" -le 10 ]; do
            gh actions-cache list -R $REPO -L 100 --sort created-at --order asc | while IFS=$'\t' read -r cacheKey _ branch _
            do
              gh actions-cache delete "$cacheKey" -R $REPO -B "$branch" --confirm
            done
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          REPO: ${{ github.repository }}