# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Please write our copyright if you use this file.
# © 2023 Floorp Projects & Contributors

on:
    workflow_call:
      secrets:
        PAT:
          description: "Personal Access Token for checkout"
          required: true
    workflow_dispatch:
jobs:
  macOS-Universal-gen-profdata-and-jarlog:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [macos-13, macos-14]
        # macos-latest-large is x86_64 and macos-latest is arm64

    steps:
      - name: Init
        run: |
          sysctl machdep.cpu
          export RUNNER_USERDIR=`echo ~`
          echo "RUNNER_USERDIR=$RUNNER_USERDIR" >> $GITHUB_ENV
          mkdir -p ~/downloads/artifacts

      - uses: actions/checkout@v4
        name: Clone 🧬
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT }}

      - name: Check Arch type
        shell: bash
        run: |
          if [[ $GHA_BUILD_MACHINE != 'macos-13' ]]; then
            export ARCH_TYPE=`echo "aarch64"`
            echo "ARCH_TYPE=$ARCH_TYPE" >> $GITHUB_ENV
          else
            export ARCH_TYPE=`echo "x86_64"`
            echo "ARCH_TYPE=$ARCH_TYPE" >> $GITHUB_ENV
          fi
        env:
          GHA_BUILD_MACHINE: ${{ matrix.runs-on }}

      - uses: actions/download-artifact@v4
        id: download-artifacts-mac-enable-profgen
        name: Download artifact 📥
        with:
          name: ssb-mac-${{ env.ARCH_TYPE }}-build-with-profgen
          path: ~/downloads/artifacts

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          # completly uninstall python3 and python3.12
          brew uninstall --ignore-dependencies python3.12 -f

          export PATH="$(python3 -m site --user-base)/bin":$PATH

          rm '/usr/local/bin/2to3-3.11' # fix Could not symlink bin/2to3-3.11
          rm '/usr/local/bin/2to3-3.12' # fix Could not symlink bin/2to3-3.12
          rm /usr/local/bin/2to3 # fix Could not symlink bin/2to3
          rm '/usr/local/bin/idle3.11' #fix Could not symlink bin/idle3.11
          rm '/usr/local/bin/idle3.12' # fix Could not symlink bin/idle3.12
          rm '/usr/local/bin/idle3' # fix Could not symlink bin/idle3
          rm '/usr/local/bin/pydoc3.11' # fix Could not symlink bin/pydoc3.11
          rm '/usr/local/bin/pydoc3.12' # fix Could not symlink bin/pydoc3.12
          rm '/usr/local/bin/pydoc3' # fix Could not symlink bin/pydoc3
          rm '/usr/local/bin/python3.11' # fix Could not symlink bin/python3.11
          rm '/usr/local/bin/python3.12' # fix Could not symlink bin/python3.12
          rm '/usr/local/bin/python3' # fix Could not symlink bin/python3
          rm '/usr/local/bin/python3.11-config' # fix Could not symlink bin/python3.11-config
          rm '/usr/local/bin/python3.12-config' # fix Could not symlink bin/python3.12-config
          rm '/usr/local/bin/python3-config' # fix Could not symlink bin/python3-config

      - name: setup environment 🌲
        run: |
          echo -e "ac_add_options --enable-bootstrap" >> mozconfig

          echo 'mozconfig: **********************'
          cat ./mozconfig
          echo '*********************************'

          brew install gnu-tar
          export PATH=/usr/local/opt/gnu-tar/libexec/gnubin:$PATH
          ./mach --no-interactive bootstrap --application-choice browser

      - name: Install setup tool via PIP 📦
        run: |
          pip install setuptools

      - name: Extract artifact 📂
        run: |
          mkdir -p ./ssb
          cp ${{ steps.download-artifacts-mac-enable-profgen.outputs.download-path }}/${ARCH_TYPE}-apple-darwin-output.tar.xz ./
          tar xf ${ARCH_TYPE}-apple-darwin-output.tar.xz

## ./mach python python/mozbuild/mozbuild/action/install.py $MOZ_FETCHES_DIR/target.dmg $MOZ_FETCHES_DIR
      - name: Generate Profdata 📊
        run: |
          ls -l ./obj-${ARCH_TYPE}-apple-darwin/dist
          ls -l ./obj-${ARCH_TYPE}-apple-darwin/dist/ssb/
          ls -l ./obj-${ARCH_TYPE}-apple-darwin/dist/ssb/Nightly.app/Contents/MacOS/

          export LLVM_PROFDATA=$RUNNER_USERDIR/.mozbuild/clang/bin/llvm-profdata
          export JARLOG_FILE="en-US.log"
          export TARGET=`sh ./build/moz.configure/../autoconf/config.guess`
          ./mach python build/pgo/profileserver.py --binary ./obj-${ARCH_TYPE}-apple-darwin/dist/ssb/Nightly.app/Contents/MacOS/ssb
        env:
          GHA_BUILD_MACHINE: ${{ matrix.runs-on }}

      - name: Publish 🎁
        uses: actions/upload-artifact@v4
        with:
          name: ssb-${{ env.ARCH_TYPE }}-apple-darwin-profdata-and-jarlog
          path: |
            merged.profdata
            en-US.log
